export enum TypeKeys {
  CRYPTOCURRENCIES_FETCH = "CRYPTOCURRENCIES_FETCH",
  CRYPTOCURRENCIES_FETCH_STOP = "CRYPTOCURRENCIES_FETCH_STOP",
  CRYPTOCURRENCIES_FETCH_FULFILLED= "CRYPTOCURRENCIES_FETCH_FULFILLED",
  CRYPTOCURRENCIES_FETCH_FAILED = "CRYPTOCURRENCIES_FETCH_FAILED",
}